In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
df = pd.read_csv("USA_Housing_Dataset.csv")

In [6]:
df.head()

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-09 00:00:00,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0,9245-9249 Fremont Ave N,Seattle,WA 98103,USA
1,2014-05-09 00:00:00,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0,33001 NE 24th St,Carnation,WA 98014,USA
2,2014-05-09 00:00:00,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0,7070 270th Pl SE,Issaquah,WA 98029,USA
3,2014-05-09 00:00:00,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0,820 NW 95th St,Seattle,WA 98117,USA
4,2014-05-10 00:00:00,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0,10834 31st Ave SW,Seattle,WA 98146,USA

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4140 entries, 0 to 4139
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4140 non-null   object
 1   price          4140 non-null   float64
 2   bedrooms       4140 non-null   float64
 3   bathrooms      4140 non-null   float64
 4   sqft_living    4140 non-null   int64
 5   sqft_lot       4140 non-null   int64
 6   floors         4140 non-null   float64
 7   waterfront     4140 non-null   int64
 8   view           4140 non-null   int64
 9   condition      4140 non-null   int64
 10  sqft_above     4140 non-null   int64
 11  sqft_basement  4140 non-null   int64
 12  yr_built       4140 non-null   int64
 13  yr_renovated   4140 non-null   int64
 14  street         4140 non-null   object
 15  city           4140 non-null   object
 16  statezip       4140 non-null   object
 17  country        4140 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 582.3+ KB

In [8]:
df.describe()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.140000e+03,4140.000000,4140.000000,4140.000000,4.140000e+03,4140.000000,4140.000000,4140.000000,4140.000000,4140.000000,4140.000000,4140.000000,4140.000000
mean,5.530629e+05,3.400483,2.163043,2143.638889,1.469764e+04,1.514130,0.007488,0.246618,3.452415,1831.351449,312.287440,1970.814010,808.368357
std,5.836865e+05,0.903939,0.784733,957.481621,3.587684e+04,0.534941,0.086219,0.790619,0.678533,861.382947,464.349222,29.807941,979.380535
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.200000e+05,3.000000,1.750000,1470.000000,5.000000e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.600000e+05,3.000000,2.250000,1980.000000,7.676000e+03,1.500000,0.000000,0.000000,3.000000,1600.000000,0.000000,1976.000000,0.000000
75%,6.591250e+05,4.000000,2.500000,2620.000000,1.100000e+04,2.000000,0.000000,0.000000,4.000000,2310.000000,602.500000,1997.000000,1999.000000
max,2.659000e+07,8.000000,6.750000,10040.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,8020.000000,4820.000000,2014.000000,2014.000000

In [10]:
# Features: sqft_living, sqft_lot, bedrooms,
# bathrooms, floors, waterfront, view, condition, yr_built

numeric_cols = df.select_dtypes(include = ['int64', 'float64'])
numeric_cols.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0
1,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0
2,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0
3,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0
4,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0

In [20]:
positive_price = len(df[df['price'] > 0])
positive_price
# 4091 < 4140
non_negative_bedrooms = len(df[df['bedrooms'] >= 0])
non_negative_bedrooms
# 4140
non_negative_bathrooms = len(df[df['bathrooms'] >= 0])
non_negative_bathrooms
# 4140

4140

In [23]:
numeric_cols = numeric_cols[numeric_cols >= 0]
numeric_cols = numeric_cols[numeric_cols['price'] > 0]
numeric_cols.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0
1,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0
2,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0
3,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0
4,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0

In [35]:
df = numeric_cols
# yr_renovated nếu không có thì ghi là 0, đang có chênh lệch rất lớn
# => Đổi thành có được tu sửa không nhé
df.loc[df['yr_renovated'] > 0, 'yr_renovated'] = 1
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
0,376000.0,3.0,2.00,1340,1384,3.0,0,0,3,1340,0,2008,0
1,800000.0,4.0,3.25,3540,159430,2.0,0,0,3,3540,0,2007,0
2,2238888.0,5.0,6.50,7270,130017,2.0,0,0,3,6420,850,2010,0
3,324000.0,3.0,2.25,998,904,2.0,0,0,3,798,200,2007,0
4,549900.0,5.0,2.75,3060,7015,1.0,0,0,5,1600,1460,1979,0

In [ ]:
from sklearn.model_selection import train_test_split
X = df.drop(columns = ['price'])
y = df['price']

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state = 36)

In [56]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_X_train = scaler.fit_transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [57]:
from sklearn.linear_model import Ridge

In [58]:
model = Ridge(alpha = 1.0, solver = 'auto', random_state = 36)
model.fit(scaled_X_train, y_train)

y_pred = model.predict(scaled_X_test)

In [59]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

In [60]:
print(mae)
print(mse)
print(r2)

152816.45924093266
48176013020.42573
0.5351538918387262

## Nguyên nhân sai số cao

Khi đọc decribe() ở đoạn đầu, ta đã thấy có giá nhà rất cao (26,5 triệu và hàng triệu, ..) trung khi trung bình mean là 550k.

Điều này cho ta biết rằng Ridge hay Linear Regression rất nhạy cảm với các Outliers như vậy